name: Deploy and Run on Test Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Deploy:
    runs-on: [self-hosted]
    
    steps:
      - name: Clone Repo or Update
        run: |
          cd ~/Docker-Compose
          if [ -d "baby_organiser/.git" ]; then
            echo "Repository already exists. Pulling latest changes..."
            cd baby_organiser
            git pull
          else
            echo "Cloning repository..."
            git clone -n --depth=1 --filter=tree:0 \
              https://github.com/Tunsworthy/baby_organiser.git
            cd baby_organiser
          fi
      
          git sparse-checkout set --no-cone /Baby_Organsier
          git checkout
      - name: Start Services with Docker Compose
        run: |
          cd ~/Docker-Compose/baby_organiser
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "POSTGRES_URI=${{ secrets.POSTGRES_URI }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "SERVER=${{ secrets.SERVER }}" >> .env
          echo "BABY_NGINX_IP=${{ secrets.BABY_NGINX_IP }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
      
          docker compose up -d

